//
//  TamBoonAPI.swift
//  TamBoon
//
//  Created by Pitiphong Phongpattranont on 7/18/2559 BE.
//  Copyright © 2559 Pitiphong Phongpattranont. All rights reserved.
//

import Foundation

/// A payment information
public struct PaymentInformation {
  /// An Omise payment token generated by Omise SDK
  public let token: String
  /// An amount of donation in THB.
  public let amount: Int
}

public enum TamBoonAPIError: ErrorType {
  case HTTPError(Int)
  case FoundationError(NSError)
  case InvalidResponse
}

public class TamBoonAPI: NSObject {
  public let host: NSURL
  private var session: NSURLSession!
  private let processingQueue: NSOperationQueue = NSOperationQueue()
  
  public init(host: NSURL) {
    self.host = host
    super.init()
    session = NSURLSession(configuration: NSURLSessionConfiguration.defaultSessionConfiguration())
  }
  
  public func listAllCharitiesWithCompletion(completion: ([Charity]?, TamBoonAPIError?) -> Void) {
    let loadCharitiesTask = session.dataTaskWithURL(host, completionHandler: { (returnedData, response, error) in
      if let error = error {
        completion(nil, .FoundationError(error))
        return
      }
      if let response = response as? NSHTTPURLResponse where !(200..<400 ~= response.statusCode) {
        completion(nil, .HTTPError(response.statusCode))
        return
      }
      
      guard let data = returnedData else {
        completion(nil, .InvalidResponse)
        return
      }
      
      let json: [[String: AnyObject]]
      do {
        if let parsedJSON = try NSJSONSerialization.JSONObjectWithData(data, options: []) as? [[String: AnyObject]] {
          json = parsedJSON
        } else {
          throw TamBoonAPIError.InvalidResponse
        }
      } catch {
        completion(nil, .InvalidResponse)
        return
      }
      
      let charities = json.flatMap(Charity.init)
      completion(charities, nil)
    })
    loadCharitiesTask.resume()
  }
  public func donateToCharity(charity: Charity, withDonatorName name: String,
                              payment: PaymentInformation,
                              completionQueue: dispatch_queue_t = dispatch_get_main_queue(),
                              completion: (TamBoonAPIError?) -> Void) -> Void {
    let donateURL = host.URLByAppendingPathComponent("donate").URLByAppendingPathComponent(String(charity.id))
    let donatingRequest = NSMutableURLRequest(URL: donateURL, cachePolicy: NSURLRequestCachePolicy.ReloadIgnoringLocalAndRemoteCacheData, timeoutInterval: 60.0)
    donatingRequest.HTTPMethod = "POST"
    
    let donatingParameter = [
      "name": name,
      "token": payment.token,
      "amount": payment.amount
    ]
    
    let donatingPayload = try! NSJSONSerialization.dataWithJSONObject(donatingParameter, options: [])
    donatingRequest.HTTPBody = donatingPayload
    
    let donatingTask = session.dataTaskWithRequest(donatingRequest) { (returnedData, response, error) in
      let donationError: TamBoonAPIError?
      defer {
        dispatch_async(completionQueue, { 
          completion(donationError)
        })
      }
      
      if let error = error {
        donationError = .FoundationError(error)
        return
      }
      if let response = response as? NSHTTPURLResponse where !(200..<400 ~= response.statusCode) {
        donationError = .HTTPError(response.statusCode)
        return
      }
      
      donationError = nil
    }
    
    donatingTask.resume()
  }
}


extension TamBoonAPI: NSURLSessionDelegate {
  
}

